name: Deploy Docs

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build and deploy documentation from"
        required: true
        default: "master"

jobs:
  deploy:
    uses: Telucero/workflows/.github/workflows/deploy-docs.yml@main
    with:
      branch: ${{ inputs.branch }}
      repository: moonbeam-foundation/moonbeam-docs
      path: moonbeam-docs
      url_prefix: moonbeam-mkdocs
